# ===========================
# ~/.zshrc (fixed + faster)
# ===========================

# ---------------------------
# Paths & environment early
# ---------------------------
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
export LANG="en_US.UTF-8"

# Prefer python3 if python is missing
if ! command -v python >/dev/null 2>&1 && command -v python3 >/dev/null 2>&1; then
  alias python=python3
fi

# SSH agent (Secretive)
export SSH_AUTH_SOCK="$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh"

# ---------------------------
# Oh My Zsh setup
# ---------------------------
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

# Plugins (keep minimal for speed)
# autoswitch_virtualenv can be costly if it scans a lot; keep it if you want it.
plugins=(git autoswitch_virtualenv)

# autoswitch-virtualenv defaults
export AUTOSWITCH_VIRTUAL_ENV_DIR="$HOME/.virtualenvs"
export AUTOSWITCH_DEFAULTENV="openai"
export ZSH_AUTOSWITCH_DEFAULT_VIRTUALENV="$HOME/.virtualenvs/openai"

# Load Oh My Zsh
source "$ZSH/oh-my-zsh.sh"

# ---------------------------
# History settings
# ---------------------------
setopt SHARE_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS
HISTSIZE=20000
SAVEHIST=20000
HISTFILE="$HOME/.zsh_history"

# Completion init (cached)
autoload -U compinit; compinit -i -C

# ---------------------------
# Aliases
# ---------------------------
alias ls='ls -G'
alias gcf='git add . && git commit -m "fix"'
alias gmd='git add . && git commit --amend'
alias top='gotop -c solarized'
alias mypy='mypy --strict --no-warn-return-any --allow-untyped-calls'

export BRIX_AVAILABLE_CLUSTERS="${BRIX_AVAILABLE_CLUSTERS},xenon,f16"

alias figure='BRIX_NAMESPACE=cft-figure BRIX_BLOBSTORE_BASE_OVERRIDE=az://oaifigure/rcall OPENAI_STORAGE_SET=oaifigure AZURE_STORAGE_ACCOUNT=oaifigure OVERRIDE_OPENAI_TEAM=custom-models OPENAI_USER=cft-figure'

# Cursor app opener
cursor() { open -a "/Applications/Cursor.app" "$@"; }

# ---------------------------
# Colors for ls
# ---------------------------
export LS_COLORS="di=34:fi=0:ln=36:pi=33:so=35:bd=34;46:cd=34;43:ex=31"
export ZLS_COLORS="$LS_COLORS"

# ---------------------------
# Prompt: lane + repo + branch (NO dirty check)
#   Dirty check was the main slowdown (git status/diff on every prompt).
# ---------------------------
setopt prompt_subst

lane_name() {
  local dir="${PWD:A}"
  case "$dir" in
    "$HOME"/code/*)
      local rest="${dir#$HOME/code/}"
      echo "${rest%%/*}"
      ;;
    "$HOME"/personal/*) echo "personal" ;;
    *) echo "" ;;
  esac
}

lane_color() {
  case "$(lane_name)" in
    gold)     echo "%F{yellow}" ;;
    silver)   echo "%F{white}" ;;
    personal) echo "%F{green}" ;;
    *)        echo "%F{cyan}" ;;
  esac
}

repo_name() {
  local top
  top="$(command git rev-parse --show-toplevel 2>/dev/null)" || return
  echo "${top:t}"
}

git_branch() {
  command git rev-parse --is-inside-work-tree &>/dev/null || return
  command git symbolic-ref --short HEAD 2>/dev/null || command git rev-parse --short HEAD 2>/dev/null
}

PROMPT='$(lane_color)[LANE: $(lane_name)]%f %F{250}[REPO: $(repo_name)]%f %F{magenta}$(git_branch)%f
%F{cyan}%~%f %# '

# ---------------------------
# nvm setup
# ---------------------------
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"

# ---------------------------
# OpenAI shrc (autogenerated) — source once
# ---------------------------
if [ -d "$HOME/.openai/shrc" ]; then
  for file in "$HOME/.openai/shrc"/*; do
    [ -f "$file" ] && source "$file"
  done
fi

# ---------------------------
# Applied devtools completions
# ---------------------------
if [ -f "$HOME/code/openai/api/applied-devtools/completions/applied_completions.zsh" ]; then
  source "$HOME/code/openai/api/applied-devtools/completions/applied_completions.zsh"
fi

# ---------------------------
# External tools (guarded)
# ---------------------------
if command -v python >/dev/null 2>&1; then
  eval "$(python -m rcall.shell 2>/dev/null || true)"
fi

if command -v am >/dev/null 2>&1; then
  eval "$(am shell)"
fi

if command -v bbb >/dev/null 2>&1; then
  eval "$(bbb complete init zsh 2>/dev/null || true)"
fi

if command -v brix >/dev/null 2>&1; then
  source <(brix completion zsh)
fi

# ---------------------------
# Line search keybindings
# ---------------------------
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

# ---------------------------
# Secrets (DO NOT COMMIT / DO NOT PASTE INTO CHAT)
# Put tokens in: ~/.config/zsh/secrets.zsh
# ---------------------------
if [ -f "$HOME/.config/zsh/secrets.zsh" ]; then
  source "$HOME/.config/zsh/secrets.zsh"
fi

# ---------------------------
# Environment include
# ---------------------------
[ -f "$HOME/.local/bin/env" ] && . "$HOME/.local/bin/env"

# ---------------------------
# Convenience helpers
# ---------------------------
vg-checkout() {
  git checkout "$@" && oaipkg poly
}

alias voncount-tui='cargo run --manifest-path "$HOME/code/openai/personal/ags/voncount/Cargo.toml" --bin voncount -- tui'
